### ISSUE TITLE
clean (extensionless) urls?

### ISSUE THREAD

**Issue by igregson** [BrowserSync/gulp-browser-sync#30]
Is it possible to use something like [clean-urls](https://preview.npmjs.com/package/clean-urls) with broswer-sync's server for extensionless .html urls?

**Comment by laurensnl** [comment]
@shakyShane  Did you get this to work? Doesn't work for me @ browser-sync 2.8.2. I get "Cannot GET /about" when I follow a link to '/about', while it should find /about.html.
