### ISSUE TITLE
Style changes do a hard reload

### ISSUE THREAD

**Issue by davej** [BrowserSync/gulp-browser-sync#44]
I'm using the generated unedited gulpfile with scss turned on. Every time I make a change to an element's scss it doesn't inject the new css, instead it does a hard reload. Using Chrome and the `gulp serve` command.

**Comment by zach-adams** [comment]
Try this thread: https://github.com/BrowserSync/gulp-browser-sync/issues/26

**Comment by shakyShane** [comment]
http://www.browsersync.io/docs/gulp/#gulp-sass-maps
