### ISSUE TITLE
Reload on Change

### ISSUE THREAD

**Issue by LynxDelli** [BrowserSync/gulp-browser-sync#48]
```js
var gulp = require('gulp');
var browserSync = require('browser-sync');
var reload = browserSync.reload;

gulp.task('js', function () {
  return gulp.src('./web/js/main.js')
    .pipe(gulp.dest('./build/js'));
});

gulp.task('watch', ['js'], function () {
  browserSync({
    proxy: "localhost"
  });
  gulp.watch(('./web/js/**/*.js',  ['js']).on('change', reload);
});
```
I want when js file is recreated reload to trigger. With this code it trigger before file is recreated in build directory. Any idea how to solve this issue?

**Comment by shinnn** [comment]
Use [`.reload({stream: true})`](http://www.browsersync.io/docs/api/#api-reload). [This example](http://www.browsersync.io/docs/gulp/#gulp-sass-css) helps you.

**Comment by shinnn** [comment]
@LynxDelli https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#question
