### ISSUE TITLE
Doesn't load with IE conditionals on body tag

### ISSUE THREAD

**Issue by jmuyskens** [BrowserSync/gulp-browser-sync#49]
We have this in our template:

    
    
    
    <body>

and BrowserSync doesn't load.

**Comment by shinnn** [comment]
https://github.com/BrowserSync/gulp-browser-sync/issues/47#issuecomment-89830275) and https://github.com/BrowserSync/browser-sync/issues/555#issuecomment-89846567

Thanks.
