### ISSUE TITLE
a problem with encoding

### ISSUE THREAD

**Issue by mice33** [BrowserSync/gulp-browser-sync#50]
File Encoding is GBK

![image](https://cloud.githubusercontent.com/assets/4945433/7384748/a02bfe04-ee6b-11e4-8155-cb6299a727c1.png)

Webpages encoding a problem, How to fix it?

**Comment by shinnn** [comment]
https://github.com/BrowserSync/gulp-browser-sync/issues/47#issuecomment-89830275
