### ISSUE TITLE
EPIPE error

### ISSUE THREAD

**Issue by onlyskyguy** [BrowserSync/gulp-browser-sync#52]
I'm getting the following error in while using Gulp/BrowserSync:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
  at exports._errnoException (util.js:746:11)
  at WriteWrap.afterWrite (net.js:775:14)
```

https://github.com/BrowserSync/browser-sync/issues/610

(anyone know how to reference that issue in gh?)

**Comment by shinnn** [comment]
https://github.com/BrowserSync/gulp-browser-sync/issues/50#issuecomment-97309945
