### ISSUE TITLE
Reloading page is really slow

### ISSUE THREAD

**Issue by boedlen** [BrowserSync/gulp-browser-sync#53]
I've recently converted our existing workflow from grunt to gulp, and i've implemented browser-sync into the flow now and i like everything but the speed i'm experiences.

I have a workflow that builds and minfies CSS and JS, uploads the files to my webserver, and the reloads the website.

I'm starting a proxy server like this:

```javascript
browserSync( {
    proxy: 'www.my-website.com'
} );
```

My gulp tasks that uploads and reloads look like this:
```javascript
    // Gulp task: Uploads all files in 'assets/css' to remote server via FTP
    gulp.task( 'ftp-css', function () {
        gulp.src( 'assets/_dist/css/*.*' )
            .pipe( ftp( cssFtpSettings ) )
            .pipe( gutil.noop() );
    } );
    // Gulp task: Uploads all files in 'assets/js' to remote server via FTP
    gulp.task( 'ftp-js', function () {
        gulp.src( 'assets/_dist/js/*.*' )
            .pipe( ftp( jsFtpSettings ) )
            .pipe( gutil.noop() );
    } );
    // Gulp task: Reload all Browsers connected to the proxy server.
    gulp.task( 'bs-reload-css', ['ftp-css'], function () {
        browserSync.reload();
    } );
    // Gulp task: Reload all Browsers connected to the proxy server.
    gulp.task( 'bs-reload-js', ['ftp-js'], function () {
        browserSync.reload();
    } );
```
### What i'm experiencing
My website has decent loadtimes when run directly and through the proxy, but when calling `browserSync.reload()` it's going crazy:

I've clicked around my site and i'm seeing loadtimes like these:
**Calling site directly** -  500ms
**Calling localhost:3000** - 500ms

But when i reload the site via browser-sync something hangs:
**Calling `browserSync.reload()`** - 13000+ms

In my scenario with FTP upload i always want to reload the entire page and never try to inject anything, can add something to force a reload everytime?

**Comment by shinnn** [comment]
1. You should `return` gulp.src stream inside gulp.task. https://github.com/gulpjs/gulp/blob/86938061512f7633567026480dca03903ac07485/docs/API.md#return-a-stream
2. Why `gutil.noop`?

**Comment by shinnn** [comment]
Please feel free to comment more if the problem still occurs though you fix [these](https://github.com/BrowserSync/gulp-browser-sync/issues/53#issuecomment-110261146).

**Comment by boedlen** [comment]
Hi @shinnn,

I changed my tasks based on your suggestions, and it solved the problem. 

Thank you for looking at my issue :smile:

**Comment by shinnn** [comment]
@boedlen No problem!

**Comment by free-minstrel** [comment]
Thank you very much, @shinnn!
Returning gulp.src stream fixes everything!
