### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Sigmanor** [BrowserSync/gulp-browser-sync#56]
Error while installing

<pre>
> bufferutil@1.1.0 install D:\Programming\gulp\sigmanor.github.io\node_modules\br
owser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_mod
ules\bufferutil
> node-gyp rebuild

|
D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\node_modules\soc
ket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil {git}{hg}
{lamb} if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_mod
ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node  rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, доб
авьте параметр "/m".
TRACKER : error TRK0005: не удалось обнаружить "CL.exe". Не удается найти указан
ный файл. [D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\node
_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferuti
l\build\bufferutil.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` faile
d with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\n
pm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:
12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\nod
e_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferuti
l
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

> utf-8-validate@1.1.0 install D:\Programming\gulp\sigmanor.github.io\node_module
s\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node
_modules\utf-8-validate
> node-gyp rebuild

D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\node_modules\soc
ket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate {git}{h
g}
{lamb} if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_mod
ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node  rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, доб
авьте параметр "/m".
TRACKER : error TRK0005: не удалось обнаружить "CL.exe". Не удается найти указан
ный файл. [D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\node
_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-val
idate\build\validation.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` faile
d with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\n
pm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:
12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\nod
e_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-val
idate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0

> utf-8-validate@1.1.0 install D:\Programming\gulp\sigmanor.github.io\node_module
s\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\
engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\node_modules\soc
ket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\w
s\node_modules\utf-8-validate {git}{hg}
{lamb} if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_mod
ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node  rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, доб
авьте параметр "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.target
s(312,5): error MSB3491: Не удалось записать строки в файл "Release\obj\validati
on\validation.tlog\validation.lastbuildstate". Слишком длинный путь или имя файл
а. Полное имя файла должно содержать меньше 260 знаков, а имя каталога - меньше
248 знаков. [D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\no
de_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client
\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` faile
d with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\n
pm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:
12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\nod
e_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\n
ode_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> bufferutil@1.1.0 install D:\Programming\gulp\sigmanor.github.io\node_modules\br
owser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engi
ne.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\node_modules\soc
ket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\w
s\node_modules\bufferutil {git}{hg}
{lamb} if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_mod
ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node  rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, доб
авьте параметр "/m".
TRACKER : error TRK0005: не удалось обнаружить "CL.exe". Не удается найти указан
ный файл. [D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\node
_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\n
ode_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` faile
d with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\n
pm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:
12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Programming\gulp\sigmanor.github.io\node_modules\browser-sync\nod
e_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\n
ode_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
browser-sync@2.8.0 node_modules\browser-sync
├── async-each-series@0.1.1
├── longest@1.0.1
├── emitter-steward@0.0.1
├── ucfirst@0.0.1
├── opn@2.0.1
├── dev-ip@1.0.1
├── query-string@2.4.0 (strict-uri-encode@1.0.1)
├── pad-left@1.0.2 (repeat-string@1.5.2)
├── ua-parser-js@0.7.9
├── browser-sync-client@2.2.1 (fresh@0.3.0, etag@1.7.0)
├── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
├── portscanner@1.0.0 (async@0.1.15)
├── connect@3.4.0 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.2.0, finalhandler@0
.4.0)
├── immutable@3.7.4
├── meow@3.3.0 (object-assign@3.0.0, camelcase-keys@1.0.0, minimist@1.1.2, indent
-string@1.2.2)
├── foxy@11.1.1 (cookie@0.1.3, http-proxy@1.11.1, lodash.merge@3.3.2)
├── resp-modifier@4.0.3 (minimatch@2.0.10)
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.2.0)
├── chokidar@1.0.5 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-par
ent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.4.0)
├── serve-index@1.7.1 (escape-html@1.0.2, parseurl@1.3.0, batch@0.5.2, http-error
s@1.3.1, debug@2.2.0, accepts@1.2.11, mime-types@2.1.3)
├── easy-extender@2.3.1 (lodash@2.4.2)
├── eazy-logger@2.1.2 (tfunk@3.0.1, opt-merger@1.1.0)
├── localtunnel@1.7.0 (debug@0.7.4, openurl@1.1.0, yargs@3.15.0, request@2.11.4)
├── lodash@3.10.0
├── browser-sync-ui@0.5.12 (connect-history-api-fallback@0.0.5, angular-touch@1.4
.3, angular-sanitize@1.4.3, angular-route@1.4.3, angular@1.4.3, stream-throttle@0
.1.3, weinre@2.0.0-pre-I0Z7U9OV)
└── socket.io@1.3.6 (debug@2.1.0, has-binary-data@0.1.3, socket.io-adapter@0.3.1,
 socket.io-parser@2.2.4, engine.io@1.5.2, socket.io-client@1.3.6)
</pre>

**Comment by shinnn** [comment]
https://github.com/BrowserSync/gulp-browser-sync/issues/55#issuecomment-123024387
