### ISSUE TITLE
browserSync issues after a change in css file

### ISSUE THREAD

**Issue by L2D22** [BrowserSync/gulp-browser-sync#64]
Hello there,
 
browserSync is so awesome, thanks for sharing it! I ran into an issue when I started a new project this week. I used the example gulp file from here https://www.browsersync.io/docs/gulp/ 

Now whenever I make a change to a css file I get this error. 
TypeError: args.cb is not a function at Object.init (../node_modules/browser-sync/lib/public/init.js:25:25)

Also, on the js side after reloading once for a change, browserSync ceases to reload again. 

Any ideas what might cause that? I tried downgrading browserSync to a previous version and various things without success. Am I missing something basic?

OSX 
10.11.2 El Captain
gulpfile
https://gist.github.com/L2D22/08b89bcf79cdcbebf2ef
package.json
https://gist.github.com/L2D22/57c2eff0fb14a3e9585a

**Comment by karneaud** [comment]
How did you overcome this issue?

**Comment by L2D22** [comment]
I don't entirely remember, but I mostly ended up using .pipe(browserSync.stream());  instead of browserSync.reload.
https://gist.github.com/L2D22/ea2af736e7f70706080f

**Comment by karneaud** [comment]
@L2D22 I ended up passing a noop function in the `init` ...

**Comment by L2D22** [comment]
Right, one more thing, I believe for the Object.init error I downgraded my browserSync version to "browser-sync": "^2.10.1"
