### ISSUE TITLE
ReferenceError: reload is not defined

### ISSUE THREAD

**Issue by eldyvoon** [BrowserSync/gulp-browser-sync#68]
ReferenceError: reload is not defined
    at Gulp.<anonymous> (/Users/James/Documents/Work/bs-recipes/recipes/gulp.sass/gulpfile.js:27:15)

**Comment by shakyShane** [comment]
Please show your entire file - I think you're trying to access a property that you havn't setup.

Closing as this is not a Browsersync issue :)
